### ISSUE TITLE
Seems that it's impossible to get it work, there're few problems

### ISSUE THREAD

**Issue by RihardsVeters** [mikeoertli/raycast-airpods-connector#3]
Problems:
1. There's no MAC address for Airpods, or I just don't know where to find it. I entered Serial number.
2. After entering serial number and running the script it shows - Airpods connected, but they don't appear in menu bar as they would if I manually connect them through bluetooth menu, and seems that they're not connected - they're paired, but they're not switched from my iPhone.

**Comment by mikeoertli** [comment]
Hi,
1. BT devices do have a MAC, but it isn't as obvious. You can manually connect them then use a CLI tool or System Profiler probably has it. I believe I used this: https://github.com/lapfelix/BluetoothConnector
2. Modern Macs/iOS devices/AirPods can connect to multiple devices. If you have them set to "automatically" connect to your devices, then in theory you don't need to switch and they're basically always connected. I personally don't like how this works so I set mine to "when last connected" on every device but my phone. Thus the need for a quick way to toggle the connection with raycast and this script.

Hope that helps.
